# Generated by Django 6.0.1 on 2026-02-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_social', models.CharField(blank=True, max_length=255)),
                ('sexo_biologico', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('intersexo', 'Intersexo'), ('nao_informado', 'Prefiro não informar')], max_length=20)),
                ('identidade_genero', models.CharField(blank=True, choices=[('mulher_cis', 'Mulher cis'), ('homem_cis', 'Homem cis'), ('mulher_trans', 'Mulher trans'), ('homem_trans', 'Homem trans'), ('nao_binario', 'Não binário'), ('outro', 'Outro'), ('nao_informado', 'Prefiro não informar')], max_length=20)),
                ('identidade_sexual', models.CharField(blank=True, choices=[('heterossexual', 'Heterossexual'), ('homossexual', 'Homossexual'), ('bissexual', 'Bissexual'), ('assexual', 'Assexual'), ('outro', 'Outro'), ('nao_informado', 'Prefiro não informar')], max_length=20)),
                ('pessoa_transexual', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=120)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('religiao', models.CharField(blank=True, choices=[('catolica', 'Católica'), ('evangelica', 'Evangélica'), ('espirita', 'Espírita'), ('umbanda', 'Umbanda'), ('candomble', 'Candomblé'), ('outra', 'Outra'), ('nao_possui', 'Não possui')], max_length=20)),
                ('religiao_desde_quando', models.CharField(blank=True, max_length=120)),
                ('identidade_etnico_racial', models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena'), ('nao_informado', 'Prefiro não informar')], max_length=20)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('uniao_estavel', 'União estável'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('nao_informado', 'Prefiro não informar')], max_length=20)),
                ('nome_mae', models.CharField(blank=True, max_length=255)),
                ('nome_pai', models.CharField(blank=True, max_length=255)),
                ('doc_certidao_nascimento', models.BooleanField(default=False)),
                ('doc_rg', models.BooleanField(default=False)),
                ('doc_cpf', models.BooleanField(default=False)),
                ('doc_ctps', models.BooleanField(default=False)),
                ('doc_titulo_eleitor', models.BooleanField(default=False)),
                ('doc_cert_escolaridade', models.BooleanField(default=False)),
                ('doc_documento_militar', models.BooleanField(default=False)),
                ('doc_cnh', models.BooleanField(default=False)),
                ('doc_ausente_certidao_1', models.BooleanField(default=False)),
                ('doc_ausente_certidao_2', models.BooleanField(default=False)),
                ('doc_ausente_rg_1', models.BooleanField(default=False)),
                ('doc_ausente_rg_2', models.BooleanField(default=False)),
                ('doc_ausente_cpf_1', models.BooleanField(default=False)),
                ('doc_ausente_cpf_2', models.BooleanField(default=False)),
                ('doc_ausente_ctps_1', models.BooleanField(default=False)),
                ('doc_ausente_ctps_2', models.BooleanField(default=False)),
                ('doc_ausente_titulo_1', models.BooleanField(default=False)),
                ('doc_ausente_titulo_2', models.BooleanField(default=False)),
                ('doc_ausente_documento_militar_1', models.BooleanField(default=False)),
                ('doc_ausente_documento_militar_2', models.BooleanField(default=False)),
                ('cpf_numero', models.CharField(blank=True, max_length=20)),
                ('rg_numero', models.CharField(blank=True, max_length=20)),
                ('titulo_eleitor_numero', models.CharField(blank=True, max_length=30)),
                ('numero_processo_pep', models.CharField(blank=True, max_length=30)),
                ('cnh_categoria', models.CharField(blank=True, choices=[('acc', 'ACC'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], max_length=3)),
                ('procedencia', models.CharField(blank=True, choices=[('unidade_prisional', 'Unidade prisional'), ('encaminhamento', 'Encaminhamento externo'), ('busca_espontanea', 'Busca espontânea'), ('outro', 'Outro')], max_length=30)),
                ('procedencia_outro', models.CharField(blank=True, max_length=120)),
                ('motivo_procura', models.TextField(blank=True)),
                ('orientado_escritorio_social', models.BooleanField(default=False)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('estado_uf', models.CharField(blank=True, max_length=2)),
                ('ponto_referencia', models.CharField(blank=True, max_length=255)),
                ('zona_cidade', models.CharField(blank=True, choices=[('norte', 'Norte'), ('sul', 'Sul'), ('leste', 'Leste'), ('oeste', 'Oeste'), ('rural', 'Rural')], max_length=10)),
                ('telefone_numero', models.CharField(blank=True, max_length=20)),
                ('telefone_contato', models.CharField(blank=True, max_length=120)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
