# Generated by Django 6.0.1 on 2026-02-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('arquivado', 'Arquivado')], default='ativo', max_length=10),
        ),
    ]
