# Generated by Django 6.0.1 on 2026-02-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cadastro_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa_atendida', models.CharField(max_length=255)),
                ('data_atendimento', models.DateField()),
                ('local_atendimento', models.CharField(blank=True, choices=[('escritorio_social', 'Escritório Social'), ('unidade_prisional', 'Unidade Prisional'), ('outro', 'Outro')], max_length=30)),
                ('tipo_atendimento', models.CharField(blank=True, choices=[('individual', 'Individual'), ('familiar', 'Familiar'), ('grupo', 'Grupo'), ('outro', 'Outro')], max_length=20)),
                ('perfil_pessoa_atendida', models.CharField(blank=True, choices=[('reeducando', 'Reeducando'), ('familiar', 'Familiar'), ('nao_cadastrado', 'Não cadastrado'), ('outro', 'Outro')], max_length=20)),
                ('motivo_procura', models.CharField(blank=True, choices=[('documentacao', 'Documentação'), ('trabalho', 'Trabalho'), ('assistencia', 'Assistência social'), ('saude', 'Saúde'), ('outro', 'Outro')], max_length=20)),
                ('objetivo_atendimento', models.CharField(blank=True, max_length=255)),
                ('profissional_responsavel', models.CharField(blank=True, max_length=120)),
                ('outras_pessoas_participantes', models.CharField(blank=True, max_length=255)),
                ('descricao_atendimento', models.TextField(blank=True)),
            ],
        ),
    ]
