# Generated by Django 6.0.1 on 2026-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cadastros/'),
        ),
    ]
