# Generated by Django 6.0.1 on 2026-02-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lembrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='curso_superior',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='estuda_atualmente',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='experiencia_escolar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='fez_ensino_superior',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='grau_instrucao',
            field=models.CharField(blank=True, choices=[('nao_informado', 'Não informado'), ('fundamental_incompleto', 'Ensino Fundamental Incompleto'), ('fundamental_completo', 'Ensino Fundamental Completo'), ('medio_incompleto', 'Ensino Médio Incompleto'), ('medio_completo', 'Ensino Médio Completo'), ('superior_incompleto', 'Ensino Superior Incompleto'), ('superior_completo', 'Ensino Superior Completo')], max_length=30),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='horario_turno_estudo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='serie_concluida',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='status_ocupacional',
            field=models.CharField(blank=True, choices=[('desempregado', 'Desempregado'), ('sem_informacao', 'Sem informação'), ('trabalhando_nm_es', 'Trabalhando via NM/ES'), ('trabalhando_ocupado', 'Trabalhando/Ocupado'), ('impedido_indisponivel', 'Impedido/Indisponível'), ('ja_trabalhou_nm_es', 'Já trabalhou via NM/ES'), ('outro', 'Outro')], max_length=30),
        ),
    ]
