# Generated by Django 6.0.1 on 2026-02-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cadastro_curso_superior_cadastro_estuda_atualmente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_social', models.CharField(blank=True, max_length=255)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo_biologico', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('intersexo', 'Intersexo'), ('nao_informado', 'Prefiro não informar')], max_length=20)),
                ('identidade_etnico_racial', models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena'), ('nao_informado', 'Prefiro não informar')], max_length=20)),
                ('pessoa_transexual', models.BooleanField(default=False)),
                ('cpf_numero', models.CharField(blank=True, max_length=20)),
                ('nis_numero', models.CharField(blank=True, max_length=30)),
                ('documentos_possui', models.TextField(blank=True)),
                ('documentos_ausentes', models.TextField(blank=True)),
                ('parentesco', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('telefone_numero', models.CharField(blank=True, max_length=20)),
                ('telefone_contato', models.CharField(blank=True, max_length=120)),
                ('telefone_observacao', models.CharField(blank=True, max_length=255)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='core.cadastro')),
            ],
        ),
    ]
