# Generated by Django 6.0.1 on 2026-02-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_familiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('realizado', 'Realizado')], default='pendente', max_length=12),
        ),
    ]
