# Generated by Django 6.0.1 on 2026-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_atendimento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='familiares/'),
        ),
    ]
