# Generated by Django 6.0.1 on 2026-02-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_familiar_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='encaminhamento',
            field=models.CharField(blank=True, choices=[('politica_publica', 'Política Pública'), ('mercado_trabalho', 'Mercado de Trabalho'), ('cursos_capacitacoes', 'Cursos e Capacitações')], max_length=30),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='encaminhamento_detalhe',
            field=models.TextField(blank=True),
        ),
    ]
