# Generated by Django 6.0.1 on 2026-02-19 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cadastro_encaminhamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='perfil_pessoa_atendida',
            field=models.CharField(blank=True, choices=[('reeducando', 'Egresso'), ('familiar', 'Familiar'), ('nao_cadastrado', 'Não cadastrado'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
