# Generated by Django 6.0.1 on 2026-02-19 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_atendimento_perfil_pessoa_atendida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='nome_interno_referencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='familiar',
            name='perfil_referencia_egresso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familiar',
            name='perfil_referencia_pre_egresso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tipo_atendimento',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('online', 'On-line'), ('grupal', 'Grupal'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='religiao',
            field=models.CharField(blank=True, choices=[('cristao', 'Cristão'), ('catolica', 'Católica'), ('evangelica', 'Evangélica'), ('espirita', 'Espírita'), ('umbanda', 'Umbanda'), ('candomble', 'Candomblé'), ('outra', 'Outra'), ('nao_possui', 'Não possui')], max_length=20),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='core.cadastro'),
        ),
    ]
